# Generated by Django 2.2.6 on 2020-05-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('preco', models.BooleanField(verbose_name='Preço')),
                ('imagem', models.ImageField(upload_to='mangueiras/imagens/', verbose_name='Imagem do Produto')),
            ],
        ),
    ]
