# Generated by Django 2.2.6 on 2020-05-20 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200520_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Preço'),
        ),
    ]
